server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    timeout: ${REDIS_TIMEOUT:60000}
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/identity_db}
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: ${DBMS_USERNAME:root}
    password: ${DBMS_PASSWORD:123456}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost:9094}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  expiration: 604800000 #ms
  refresh-expiration: 2592000000 #ms

google:
  client-id: "32893351040-e670bshbm89vqp6pnasv97pj7t294khn.apps.googleusercontent.com"
  client-secret: "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"
  redirect-uri: "http://localhost:3000/authenticate"

