server:
  port: 8888
app:
  api-prefix: /api/v1
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            # Route 1: Identity Service
            - id: identity-service
              uri: http://localhost:8080
              predicates:
                - Path= ${app.api-prefix}/identity/**
              filters:
                - StripPrefix=2
            # Route 2: Profile Service
            - id: profile-service
              uri: http://localhost:8081
              predicates:
                - Path=${app.api-prefix}/profile/**
              filters:
                - StripPrefix=2

            # Route 2.1: Subscription Service
            - id: profile-service
              uri: http://localhost:8081
              predicates:
                - Path=${app.api-prefix}/subscription/**
              filters:
                - StripPrefix=2
            # Route 2.2: Membership Service
            - id: profile-service
              uri: http://localhost:8081
              predicates:
                - Path=${app.api-prefix}/memberships/**
              filters:
                - StripPrefix=2
            # Route 2.3: Membership Service
            - id: profile-service
              uri: http://localhost:8081
              predicates:
                - Path=${app.api-prefix}/payments/**
              filters:
                - StripPrefix=2

            # Route 3: Notification Service
            - id: notification-service
              uri: http://localhost:8082
              predicates:
                - Path=${app.api-prefix}/notification/**
              filters:
                - StripPrefix=2
            # Route 4: Post Service
            - id: post-service
              uri: http://localhost:8083
              predicates:
                - Path=${app.api-prefix}/post/**
              filters:
                - StripPrefix=2
            # Route 5: Ai Service
            - id: ai-service
              uri: http://localhost:8084
              predicates:
                - Path=${app.api-prefix}/ai/**
              filters:
                - StripPrefix=2
            # Route 5: Video Service
            - id: video-service
              uri: http://localhost:8085
              predicates:
                - Path=${app.api-prefix}/video/**
              filters:
                - StripPrefix=2
            # Route 5: Video Service
            - id: video-service
              uri: http://localhost:8085
              predicates:
                - Path=${app.api-prefix}/playlist/**
              filters:
                - StripPrefix=2
            # Route 6: Comment Service
            - id: comment-service
              uri: http://localhost:8086
              predicates:
                - Path=${app.api-prefix}/comment/**
              filters:
                - StripPrefix=2