server:
  port: 8085
spring:
  application:
    name: video-service
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  datasource:
    url: jdbc:postgresql://localhost:5432/video_db
    username: ${DBMS_USERNAME:postgres}
    password: ${DBMS_PASSWORD:123456}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost:9094}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
springdoc:
  group-configs:
    - group: video
      paths-to-match: /video/**
    - group: playlist
      paths-to-match: /playlist/**

aws:
  s3:
    bucket-name: profile-image-s3
    region: ap-southeast-1   # Singapore region
    access-key:
    secret-key: