server:
  port: 8088
  servlet:
    context-path: /file
spring:
  application:
    name: file-service
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
aws:
  s3:
    bucket-name: profile-image-s3
    region: ap-southeast-1   # Singapore region
    access-key: your-access-key
    secret-key: your-secret-key