server:
  port: 8081
spring:
  application:
    name: profile-service
  datasource:
    url: ${DBMS_CONNECTION:jdbc:postgresql://localhost:5432/profile_db}
    username: ${DBMS_USERNAME:postgres}
    password:  ${DBMS_PASSWORD:123456}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost:9094}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
springdoc:
  group-configs:
    - group: profile
      paths-to-match: /profile/**
    - group: internal
      paths-to-match: /internal/profile/**
paypal:
  client-id:
  client-secret:
  mode: sandbox # sandbox hoáº·c live
  success-url: ${app.frontend-url}/membership/success
  cancel-url: ${app.frontend-url}/membership/cancel
app:
  frontend-url: http://localhost:3000