server:
  port: 8081
spring:
  application:
    name: profile-service
  datasource:
    url: ${DBMS_CONNECTION:jdbc:postgresql://localhost:5432/profile_db}
    username: ${DBMS_USERNAME:postgres}
    password:  ${DBMS_PASSWORD:123456}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
springdoc:
  group-configs:
    - group: profile
      paths-to-match: /profile/**
    - group: internal
      paths-to-match: /internal/profile/**
paypal:
  client-id: AXGhOWS38swe3N1OXVAHBn7NgN-LO4_bDLgQSiq-sJaqZ6dr4b5s9O081f8hT2kBhz7Lb67dqWvymKOu
  client-secret: ENw7SI0Zw7QAraH6xxEEDcP8XiTHeXxDW-RoWsh3QVBaSKxmHr6aat9qBEscwqGEyUHNEg_zU0U4j8fR
  mode: sandbox # sandbox hoáº·c live
  success-url: ${app.frontend-url}/membership/success
  cancel-url: ${app.frontend-url}/membership/cancel
app:
  frontend-url: http://localhost:3000