server:
  port: 8081
spring:
  application:
    name: profile-service
  datasource:
    url: ${DBMS_CONNECTION:jdbc:postgresql://localhost:5432/profile_db}
    username: ${DBMS_USERNAME:postgres}
    password:  ${DBMS_PASSWORD:123456}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
springdoc:
  group-configs:
    - group: profile
      paths-to-match: /profile/**
    - group: internal
      paths-to-match: /internal/profile/**
paypal:
  client-id: Ab2FU5u97cgWPv2X7decFTugtAHIpMcD7RCOwaJQ033uD4H_bI7qTmmtcp2wxXIuDhhjNxF8r43Od2fg
  client-secret: ELBp27evxbc7eI6GWs4RLB_KAyrswZZfIpvQmM9TdBG-7kcYo75t6Ht7ynYYsSmjLNV4rtNSWQBcx2bz
  mode: sandbox # sandbox hoáº·c live
  success-url: ${app.frontend-url}/membership/success
  cancel-url: ${app.frontend-url}/membership/cancel
app:
  frontend-url: http://localhost:3000